
// module: 产品信息
// 企业产品的分类展示，搜索，详情
// 原型地址: http://localhost:8080/product/index.html
// 主要流程参考：http://localhost:8080/product/index.html
// 任务列表：参考tapd

### 产品分类
# 获取产品分类数组列表
# response: Array<{name: string, id: number}>
GET {{host}}/api/product/category
Authorization: {{token}}
X-APP: {{appId}}

### 产品列表
# Request: sk: 搜索关键字, cid: number 类别id
# Response: array<{id: number, name: string, price: number, image: string, category: string}>
# model: j\httpDoc\example\model\Product
# viewType: list
GET {{host}}/api/product/search?sk=&cid=
Authorization: {{token}}
X-APP: {{appId}}

### 产品详情
# model: j\httpDoc\example\model\Product
# viewType: detail
GET {{host}}/api/product/info?id=1
Authorization: {{token}}
X-APP: {{appId}}
